//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Areas.Admin.Data
{

    public partial class Book
    {
        public int Book_id { get; set; }
        public int Book_author_id { get; set; }
        public int Book_genre_id { get; set; }
        public int Book_publisher_id { get; set; }
        public int Book_language_id { get; set; }
        public string Book_title { get; set; }
        public int Book_edition { get; set; }
        public int Book_edition_year { get; set; }
        public int Book_pages { get; set; }
        public double Book_price { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Language Language { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
