//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAccount
    {
        public int user_id { get; set; }
        public Nullable<int> user_permission { get; set; }
        public string user_account_name { get; set; }
        public string user_passwd { get; set; }
        public string user_mail { get; set; }
        public string user_name { get; set; }
        public string user_mid_name { get; set; }
        public string user_last_name { get; set; }
        public int user_age { get; set; }
        public string user_phone_number { get; set; }
    }
}
